FROM php:7.4-apache
RUN docker-php-ext-install mysqli


# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Copy local code to the container image.
COPY . /public
WORKDIR /public